sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

notifications:
  email:
    on_success: never
    on_failure: always

language: php

matrix:
  include:
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge
    - php: nightly
    - php: 8.0
    - php: 7.4
    - php: 7.3
    - php: 7.2
      env: LINT=true

  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install

script:
  - if [[ $LINT = true ]]; then
      composer cs-lint;
    fi
  - composer test
